use anyhow::{Context, Result, bail};
use serde_json::{Value, json};

use crate::stats::MatchSummary;
use crate::summary::Summary;

/// A PNG (or other) file attached to a webhook message. Reference it from an
/// embed with `attachment://<filename>`.
pub struct Attachment {
    pub filename: String,
    pub bytes: Vec<u8>,
}

/// A Discord incoming webhook the embeds are POSTed to.
pub struct Webhook {
    url: String,
    http: reqwest::Client,
}

impl Webhook {
    pub fn new(url: String) -> Self {
        Self {
            url,
            http: reqwest::Client::new(),
        }
    }

    /// Post embeds (and any attachments) as a single webhook message. With
    /// attachments the request is multipart (`payload_json` + `files[i]`).
    pub async fn post(&self, embeds: &[Value], attachments: &[Attachment]) -> Result<()> {
        let payload = json!({ "embeds": embeds });
        let builder = if attachments.is_empty() {
            self.http.post(&self.url).json(&payload)
        } else {
            let mut form = reqwest::multipart::Form::new().text(
                "payload_json",
                serde_json::to_string(&payload).context("serializing webhook payload")?,
            );
            for (i, a) in attachments.iter().enumerate() {
                let part = reqwest::multipart::Part::bytes(a.bytes.clone())
                    .file_name(a.filename.clone())
                    .mime_str("image/png")
                    .context("building attachment part")?;
                form = form.part(format!("files[{i}]"), part);
            }
            self.http.post(&self.url).multipart(form)
        };

        let resp = builder.send().await.context("posting to Discord webhook")?;
        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            bail!("Discord webhook returned {status}: {body}");
        }
        Ok(())
    }
}

/// The stats grid as a single Discord embed (the inner object, not the wrapper).
pub fn stats_embed(s: &MatchSummary) -> Value {
    let (result, color) = if s.win {
        ("Victory", 0x2ecc71)
    } else {
        ("Defeat", 0xe74c3c)
    };
    let mins = s.duration_secs / 60;
    let secs = s.duration_secs % 60;

    json!({
        "author": { "name": s.player, "url": s.profile_url },
        "title": format!("{} — {result}", s.champion),
        "url": s.profile_url,
        "color": color,
        "thumbnail": { "url": s.icon_url },
        "fields": [
            { "name": "KDA", "value": format!("{}/{}/{} ({:.2})", s.kills, s.deaths, s.assists, s.kda()), "inline": true },
            { "name": "CS", "value": format!("{} ({:.1}/min)", s.cs, s.cs_per_min), "inline": true },
            { "name": "Duration", "value": format!("{mins}:{secs:02}"), "inline": true },
            { "name": "Wards", "value": format!(
                "{} placed · {} killed · {} control",
                s.vision.wards_placed, s.vision.wards_killed, s.vision.control_wards_bought),
                "inline": false },
        ],
        "footer": { "text": "scry" }
    })
}

/// The coach breakdown as a Discord embed: the `Verdict` section becomes the
/// description, every other section becomes a field. Bodies are truncated to
/// Discord's limits.
pub fn coach_embed(summary: &Summary, model: &str) -> Value {
    let mut description = String::new();
    let mut fields: Vec<Value> = Vec::new();
    for (heading, body) in &summary.sections {
        if heading.eq_ignore_ascii_case("Verdict") {
            description = truncate(body, 4096);
        } else {
            fields.push(json!({
                "name": heading,
                "value": truncate(body, 1024),
                "inline": false,
            }));
        }
    }
    json!({
        "title": "📜 Coach's Breakdown",
        "color": 0x9b59b6,
        "description": description,
        "fields": fields,
        // AI-generated: attribute the model and warn the reader it can be wrong.
        "footer": { "text": format!("Generated by {model}") },
    })
}

/// Truncate to at most `max` characters, appending an ellipsis if cut.
fn truncate(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        s.to_string()
    } else {
        let kept: String = s.chars().take(max.saturating_sub(1)).collect();
        format!("{kept}…")
    }
}
